sudo: false
language: node_js
cache:
  npm: false
notifications:
  email: false
node_js:
  - lts/*
before_install:
  - npm i -g npm@^6.14.11
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release